FROM ghcr.io/oracle/oraclelinux8-nodejs:20-20231221
RUN echo 'Setting up packages' \
&& yum update \
&& yum install -y \
git \
rsync \
jq \
make \
nano \
vim \
lsof \
unzip \
zip \
python3.11 \
cargo \
sudo \
chsh \
zsh
RUN echo 'Setting up dev user' \
&& groupadd -g 1000 dev \
&& useradd -u 1000 -g 1000 dev \
&& usermod -aG wheel dev \
&& echo 'dev, %dev  ALL : (ALL) ALL' >> /etc/sudoers \ 
&& echo 'Setting dev user password to ADMIN123#' \
&& echo "dev:ADMIN#123" | chpasswd

USER dev
WORKDIR /home/dev

RUN echo 'Getting pnpm' \
&& curl -fsSL https://get.pnpm.io/install.sh | sh - \
&& source /home/dev/.bashrc